/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazjose;

import aaaaa.Consulta_Usuarios;
import aaaaa.Usuarios;
import ctrl.ControlUsuarios;

/**
 *
 * @author JOSE MUÑOS
 */
public class RecuperarContraseña extends javax.swing.JFrame {

    /**
     * Creates new form RecuperarContraseña
     */
    public RecuperarContraseña() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Usuario = new javax.swing.JTextField();
        Enviar = new interfazjose.MyButton();
        jLabel2 = new javax.swing.JLabel();
        Gmail = new javax.swing.JTextField();
        Salir = new interfazjose.MyButton();
        myButton1 = new interfazjose.MyButton();
        Inicio = new interfazjose.MyButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Ingrese su Usuario para recuperar su contraseña");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setText("¿Olvidaste tu contraseña? ");

        Usuario.setBackground(new java.awt.Color(51, 51, 51));
        Usuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Usuario.setForeground(new java.awt.Color(204, 204, 204));
        Usuario.setToolTipText("Ingrese su Usuario para recuperar su contraseña");
        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });

        Enviar.setBackground(new java.awt.Color(51, 51, 51));
        Enviar.setText("Enviar");
        Enviar.setBorderColor(new java.awt.Color(153, 153, 153));
        Enviar.setColor(new java.awt.Color(51, 51, 51));
        Enviar.setColorClick(new java.awt.Color(153, 153, 153));
        Enviar.setColorOver(new java.awt.Color(51, 51, 51));
        Enviar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Enviar.setRadius(25);
        Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Su Clave se Envió al Siguiente Correo: ");

        Gmail.setBackground(new java.awt.Color(51, 51, 51));
        Gmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Gmail.setForeground(new java.awt.Color(204, 204, 204));
        Gmail.setToolTipText("Correo al cual fue enviado la contraseña");
        Gmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(Gmail, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Gmail, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 500, 420));

        Salir.setForeground(new java.awt.Color(204, 204, 204));
        Salir.setText("Salir");
        Salir.setBorderColor(new java.awt.Color(0, 0, 0));
        Salir.setColor(new java.awt.Color(102, 0, 51));
        Salir.setColorClick(new java.awt.Color(255, 0, 102));
        Salir.setColorOver(new java.awt.Color(204, 0, 102));
        Salir.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Salir.setRadius(25);
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 460, 80, 30));

        myButton1.setForeground(new java.awt.Color(204, 204, 204));
        myButton1.setText("Registro");
        myButton1.setBorderColor(new java.awt.Color(51, 102, 0));
        myButton1.setColor(new java.awt.Color(0, 153, 0));
        myButton1.setColorClick(new java.awt.Color(0, 102, 51));
        myButton1.setColorOver(new java.awt.Color(51, 153, 0));
        myButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        myButton1.setRadius(25);
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(myButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 90, -1));

        Inicio.setForeground(new java.awt.Color(51, 51, 51));
        Inicio.setText("Iniciar sesion");
        Inicio.setActionCommand("Iniciar sesión");
        Inicio.setBorderColor(new java.awt.Color(204, 204, 0));
        Inicio.setColor(new java.awt.Color(255, 255, 51));
        Inicio.setColorClick(new java.awt.Color(255, 255, 102));
        Inicio.setColorOver(new java.awt.Color(255, 204, 0));
        Inicio.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Inicio.setRadius(25);
        Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioActionPerformed(evt);
            }
        });
        jPanel1.add(Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagen-papel-tapiz-fondo-pintura-acrilica-gris_53876-104021.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 760, 510));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarActionPerformed
 Usuarios usuarios = new Usuarios();
        Consulta_Usuarios consulta_Usuarios = new Consulta_Usuarios();
        String user;
        user=this.Usuario.getText();
        ControlUsuarios ctrl=new ControlUsuarios(usuarios, consulta_Usuarios);
        ctrl.Iniciar();
        if(ctrl.Enviar(user)){
            this.Usuario.setText("");
            this.Gmail.setText(ctrl.destinatario);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_EnviarActionPerformed

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
Registro registroPanel = new Registro();
registroPanel.setVisible(true);
this.setVisible(false);
    }//GEN-LAST:event_myButton1ActionPerformed

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioActionPerformed

    private void GmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GmailActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        this.setVisible(false);
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirActionPerformed

    private void InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioActionPerformed
        Inicio inicioPanel = new Inicio();
        inicioPanel.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_InicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecuperarContraseña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private interfazjose.MyButton Enviar;
    private javax.swing.JTextField Gmail;
    private interfazjose.MyButton Inicio;
    private interfazjose.MyButton Salir;
    private javax.swing.JTextField Usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private interfazjose.MyButton myButton1;
    // End of variables declaration//GEN-END:variables
}
