/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazjose;

import aaaaa.Consulta_Usuarios;
import aaaaa.Usuarios;
import ctrl.ControlUsuarios;

/**
 *
 * @author JOSE MUÑOS
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
         this.Ocultar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Gmail = new javax.swing.JTextField();
        myButton2 = new interfazjose.MyButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Ver = new javax.swing.JLabel();
        Ocultar = new javax.swing.JLabel();
        Usuario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Contraseña = new javax.swing.JPasswordField();
        Registro = new interfazjose.MyButton();
        Salir1 = new interfazjose.MyButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Radiant-fotor-20231105154626 (1).png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, -40, 310, 200));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Usuario ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setText("Formulario de registro");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 430, 90));

        Gmail.setBackground(new java.awt.Color(51, 51, 51));
        Gmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Gmail.setForeground(new java.awt.Color(204, 204, 204));
        Gmail.setToolTipText("Ingrese su correo");
        Gmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GmailActionPerformed(evt);
            }
        });
        jPanel2.add(Gmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 417, 34));

        myButton2.setBackground(new java.awt.Color(51, 51, 51));
        myButton2.setText("Registrate");
        myButton2.setBorderColor(new java.awt.Color(153, 153, 153));
        myButton2.setColor(new java.awt.Color(51, 51, 51));
        myButton2.setColorClick(new java.awt.Color(153, 153, 153));
        myButton2.setColorOver(new java.awt.Color(51, 51, 51));
        myButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        myButton2.setRadius(25);
        myButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(myButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 420, 33));

        jLabel2.setText("Contraseña*");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, 20));

        jLabel6.setText("¿Ya tienes cuenta?");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 130, 20));

        Ver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ver_32px.png"))); // NOI18N
        Ver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VerMouseClicked(evt);
            }
        });
        jPanel2.add(Ver, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, -1, 30));

        Ocultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ocultar_32px.png"))); // NOI18N
        Ocultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OcultarMouseClicked(evt);
            }
        });
        jPanel2.add(Ocultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, -1, 30));

        Usuario.setBackground(new java.awt.Color(51, 51, 51));
        Usuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Usuario.setForeground(new java.awt.Color(204, 204, 204));
        Usuario.setToolTipText("Ingrese su nombre de usuario");
        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 417, 34));

        jLabel8.setText("Correo*");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Iniciar sesión");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 120, 20));

        Contraseña.setBackground(new java.awt.Color(51, 51, 51));
        Contraseña.setForeground(new java.awt.Color(204, 204, 204));
        Contraseña.setToolTipText("Ingrese la contraseña");
        Contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaActionPerformed(evt);
            }
        });
        jPanel2.add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 417, 33));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 530, 440));

        Registro.setForeground(new java.awt.Color(204, 204, 204));
        Registro.setText("Iniciar sesion");
        Registro.setActionCommand("Iniciar sesión");
        Registro.setBorderColor(new java.awt.Color(51, 102, 0));
        Registro.setColor(new java.awt.Color(0, 153, 0));
        Registro.setColorClick(new java.awt.Color(0, 102, 51));
        Registro.setColorOver(new java.awt.Color(51, 153, 0));
        Registro.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Registro.setRadius(25);
        Registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroActionPerformed(evt);
            }
        });
        jPanel1.add(Registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 130, -1));

        Salir1.setForeground(new java.awt.Color(204, 204, 204));
        Salir1.setText("Salir");
        Salir1.setBorderColor(new java.awt.Color(0, 0, 0));
        Salir1.setColor(new java.awt.Color(102, 0, 51));
        Salir1.setColorClick(new java.awt.Color(255, 0, 102));
        Salir1.setColorOver(new java.awt.Color(204, 0, 102));
        Salir1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Salir1.setRadius(25);
        Salir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salir1ActionPerformed(evt);
            }
        });
        jPanel1.add(Salir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 460, 80, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagen-papel-tapiz-fondo-pintura-acrilica-gris_53876-104021.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 490));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void myButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton2ActionPerformed
          Usuarios usuarios = new Usuarios();
        Consulta_Usuarios consulta_Usuarios = new Consulta_Usuarios();
        String user,correo,clave;
        user=this.Usuario.getText();
        correo=this.Gmail.getText();
        clave=this.Contraseña.getText();
        ControlUsuarios ctrl=new ControlUsuarios(usuarios, consulta_Usuarios);
        if(ctrl.Guardar(user, correo, clave)){
            this.Usuario.setText("");
            this.Gmail.setText("");
            this.Contraseña.setText("");
        }
        
    }//GEN-LAST:event_myButton2ActionPerformed

    private void VerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerMouseClicked
        Ver.setVisible(false);
        Ocultar.setVisible(true);
        Contraseña.setEchoChar((char)0);
    }//GEN-LAST:event_VerMouseClicked

    private void OcultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OcultarMouseClicked
        Ver.setVisible(true);
        Ocultar.setVisible(false);
        Contraseña.setEchoChar('*');  

    }//GEN-LAST:event_OcultarMouseClicked

    private void RegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroActionPerformed
       Inicio inicioPanel = new Inicio(); 
    inicioPanel.setVisible(true); 
    this.setVisible(false); 
    }//GEN-LAST:event_RegistroActionPerformed

    private void GmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GmailActionPerformed

    private void ContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
     Inicio inicioPanel = new Inicio();
    inicioPanel.setVisible(true); 
    this.setVisible(false); 
    }//GEN-LAST:event_jLabel7MouseClicked

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioActionPerformed

    private void Salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salir1ActionPerformed
        this.setVisible(false);
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_Salir1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Contraseña;
    private javax.swing.JTextField Gmail;
    private javax.swing.JLabel Ocultar;
    private interfazjose.MyButton Registro;
    private interfazjose.MyButton Salir1;
    private javax.swing.JTextField Usuario;
    private javax.swing.JLabel Ver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private interfazjose.MyButton myButton2;
    // End of variables declaration//GEN-END:variables
}
